# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: kmd6851@psu.edu
author_name: Kaylee de Soto
create_example_module: false
custom_install: true
enforce_style:
- pylint
- black
- isort
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: superphot_plus
project_license: MIT
project_name: superphot-plus
project_organization: VTDA-Group
python_versions:
- '3.9'
- '3.10'
- '3.11'
